/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.CreatePersonHistory;
import Business.CreatePerson;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author SUNREN
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     * @param 
     */
    private CreatePersonHistory cph;
    private String filePath;
    public CreateJPanel(CreatePersonHistory cph) {
        initComponents();
        this.cph = cph;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblDataofBirth = new javax.swing.JLabel();
        lblFAXNumbe = new javax.swing.JLabel();
        lblSocialSecurityNumber = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDataofbirth = new javax.swing.JTextField();
        txtFAXNumber = new javax.swing.JTextField();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtGographicData = new javax.swing.JTextField();
        txtTelephoneNum = new javax.swing.JTextField();
        txtEmailAdd = new javax.swing.JTextField();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtDeviceIdentifiers = new javax.swing.JTextField();
        txtCertificatecenseNumber = new javax.swing.JTextField();
        txtBankAccountNumbers = new javax.swing.JTextField();
        txtVehicleIdentifiers = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtHealthPlanBeneficiaryNumber = new javax.swing.JTextField();
        txtBiometricIdentifiers = new javax.swing.JTextField();
        txtInternetProtocolAddresses = new javax.swing.JTextField();
        lblTemp1 = new javax.swing.JLabel();
        lblBloodPressure1 = new javax.swing.JLabel();
        lblPulse1 = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        lblgographicData = new javax.swing.JLabel();
        lblTelephoneNumbers = new javax.swing.JLabel();
        lblEmailAddresses = new javax.swing.JLabel();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblTemp3 = new javax.swing.JLabel();
        lblBloodPressure3 = new javax.swing.JLabel();
        lblPulse3 = new javax.swing.JLabel();
        lblDate3 = new javax.swing.JLabel();
        btnupload = new javax.swing.JButton();
        lblgographicData1 = new javax.swing.JLabel();
        txtUniqueCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblName.setText("Name");

        lblDataofBirth.setText("Data of Birth");

        lblFAXNumbe.setText("FAXNumber");

        lblSocialSecurityNumber.setText("Social Security Number");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtDataofbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataofbirthActionPerformed(evt);
            }
        });

        txtFAXNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAXNumberActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Create");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtGographicData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGographicDataActionPerformed(evt);
            }
        });

        txtTelephoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNumActionPerformed(evt);
            }
        });

        txtEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddActionPerformed(evt);
            }
        });

        txtDeviceIdentifiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceIdentifiersActionPerformed(evt);
            }
        });

        txtCertificatecenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificatecenseNumberActionPerformed(evt);
            }
        });

        txtBankAccountNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccountNumbersActionPerformed(evt);
            }
        });

        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });

        txtHealthPlanBeneficiaryNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthPlanBeneficiaryNumberActionPerformed(evt);
            }
        });

        txtBiometricIdentifiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiometricIdentifiersActionPerformed(evt);
            }
        });

        txtInternetProtocolAddresses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInternetProtocolAddressesActionPerformed(evt);
            }
        });

        lblTemp1.setText("Health Plan Beneficiary Number");

        lblBloodPressure1.setText("Certificate cense Number");

        lblPulse1.setText("Device Identifiers");

        lblDate1.setText("Internet Protocol Addresses");

        lblgographicData.setText("Gographic Data");

        lblTelephoneNumbers.setText("Telephone Numbers");

        lblEmailAddresses.setText("Email Addresses");

        lblMedicalRecordNumber.setText("Medical Record Number;");

        lblTemp3.setText("Bank Account Numbers");

        lblBloodPressure3.setText("Vehicle Identifiers");

        lblPulse3.setText("LinkedIn");

        lblDate3.setText("Biometric Identifiers");

        btnupload.setText("Image upload");
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        lblgographicData1.setText("Unique Code");

        txtUniqueCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueCodeActionPerformed(evt);
            }
        });

        jLabel2.setText("Full Face Photos And Comparable Images");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(432, 432, 432))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTemp1)
                    .addComponent(lblBloodPressure1)
                    .addComponent(lblPulse1)
                    .addComponent(lblDate1)
                    .addComponent(lblName)
                    .addComponent(lblDataofBirth)
                    .addComponent(lblFAXNumbe)
                    .addComponent(lblSocialSecurityNumber)
                    .addComponent(lblgographicData1))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtName)
                        .addComponent(txtDataofbirth)
                        .addComponent(txtFAXNumber)
                        .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDeviceIdentifiers)
                        .addComponent(txtCertificatecenseNumber)
                        .addComponent(txtHealthPlanBeneficiaryNumber)
                        .addComponent(txtInternetProtocolAddresses, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtUniqueCode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailAddresses)
                    .addComponent(lblMedicalRecordNumber)
                    .addComponent(lblTemp3)
                    .addComponent(lblBloodPressure3)
                    .addComponent(lblPulse3)
                    .addComponent(lblDate3)
                    .addComponent(lblTelephoneNumbers)
                    .addComponent(lblgographicData)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(txtBankAccountNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtGographicData)
                        .addComponent(txtTelephoneNum)
                        .addComponent(txtEmailAdd)
                        .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtVehicleIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBiometricIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupload))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataofBirth)
                            .addComponent(txtDataofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFAXNumbe)
                            .addComponent(txtFAXNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSocialSecurityNumber)
                            .addComponent(lblMedicalRecordNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGographicData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblgographicData))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelephoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelephoneNumbers))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmailAddresses)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTemp3)
                        .addGap(28, 28, 28)
                        .addComponent(lblBloodPressure3)
                        .addGap(28, 28, 28)
                        .addComponent(lblPulse3)
                        .addGap(31, 31, 31)
                        .addComponent(lblDate3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHealthPlanBeneficiaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBankAccountNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCertificatecenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeviceIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBiometricIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInternetProtocolAddresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTemp1)
                        .addGap(28, 28, 28)
                        .addComponent(lblBloodPressure1)
                        .addGap(28, 28, 28)
                        .addComponent(lblPulse1)
                        .addGap(31, 31, 31)
                        .addComponent(lblDate1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgographicData1)
                    .addComponent(txtUniqueCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupload)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addComponent(btnSave)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFAXNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAXNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAXNumberActionPerformed

    private void txtDataofbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataofbirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataofbirthActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String name = txtName.getText();
        String DateofBirth = txtDataofbirth.getText();
        String gogrphicDate = txtGographicData.getText();
        String TelephoneNumbers = txtTelephoneNum.getText();
	String FAXNumber = txtFAXNumber.getText();
	String EmailAddresses = txtEmailAdd.getText();
	String SocialSecurityNumber = txtSocialSecurityNumber.getText();
	String MedicalRecordNumber = txtMedicalRecordNumber.getText();
	String HealthPlanBeneficiaryNumber = txtHealthPlanBeneficiaryNumber.getText();
	String BankAccountNumbers = txtBankAccountNumbers.getText();
	String CertificatecenseNumber = txtCertificatecenseNumber.getText();
	String VehicleIdentifiers = txtVehicleIdentifiers.getText();
	String DeviceIdentifiers = txtDeviceIdentifiers.getText();
	String LinkedIn = txtLinkedIn.getText();
	String InternetProtocolAddresses = txtInternetProtocolAddresses.getText();
	String BiometricIdentifiers = txtBiometricIdentifiers.getText();
        String UniqueCode = txtUniqueCode.getText();
       
        CreatePerson c = cph.addVital();
        c.setName(name);
        c.setDateOfBirth(DateofBirth);
        c.setGographicData(gogrphicDate);
        c.setTelephoneNumbers(TelephoneNumbers);
        c.setFAXNumber(FAXNumber);
        c.setEmailAddresses(EmailAddresses);
        c.setSocialSecurityNumber(SocialSecurityNumber);
        c.setMedicalRecordNumber(MedicalRecordNumber);
        c.setHealthPlanBeneficiaryNumber(HealthPlanBeneficiaryNumber);
        c.setBankAccountNumbers(BankAccountNumbers);
        c.setCertificatecenseNumber(CertificatecenseNumber);
        c.setVehicleIdentifiers(VehicleIdentifiers);
        c.setDeviceIdentifiers(DeviceIdentifiers);
        c.setLinkedIn(LinkedIn);
        c.setInternetProtocolAddresses(InternetProtocolAddresses);
        c.setBiometricIdentifiers(BiometricIdentifiers);
        c.setFilePath(filePath);
        c.setUniqueCode(UniqueCode);

        JOptionPane.showMessageDialog(null, "Create Successfully");
        txtName.setText("");
        txtDataofbirth.setText("");
        txtGographicData.setText("");
        txtSocialSecurityNumber.setText("");
        txtTelephoneNum.setText("");
        txtFAXNumber.setText("");
        txtEmailAdd.setText("");
        txtSocialSecurityNumber.setText("");
        txtMedicalRecordNumber.setText("");
        txtHealthPlanBeneficiaryNumber.setText("");
        txtBankAccountNumbers.setText("");
        txtCertificatecenseNumber.setText("");
        txtVehicleIdentifiers.setText("");
        txtDeviceIdentifiers.setText("");
        txtLinkedIn.setText("");
        txtInternetProtocolAddresses.setText("");
        txtBiometricIdentifiers.setText("");
        txtUniqueCode.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtGographicDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGographicDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGographicDataActionPerformed

    private void txtTelephoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneNumActionPerformed

    private void txtEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddActionPerformed

    private void txtDeviceIdentifiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceIdentifiersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdentifiersActionPerformed

    private void txtCertificatecenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificatecenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificatecenseNumberActionPerformed

    private void txtBankAccountNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccountNumbersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccountNumbersActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtHealthPlanBeneficiaryNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthPlanBeneficiaryNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthPlanBeneficiaryNumberActionPerformed

    private void txtBiometricIdentifiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiometricIdentifiersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiometricIdentifiersActionPerformed

    private void txtInternetProtocolAddressesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInternetProtocolAddressesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInternetProtocolAddressesActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        JFileChooser chooser = new JFileChooser(); 
        chooser.setMultiSelectionEnabled(true);
        int returnVal = chooser.showOpenDialog(btnupload);
        if (returnVal == JFileChooser.APPROVE_OPTION) {          
        String filepath = chooser.getSelectedFile().getAbsolutePath();       
        String filename = chooser.getSelectedFile().getName();
        this.filePath = filepath;
        System.out.println(filepath);
        }  
    }//GEN-LAST:event_ButtonActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
         System.out.print("111");
    }//GEN-LAST:event_formMouseClicked

    private void txtUniqueCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueCodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnupload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBloodPressure1;
    private javax.swing.JLabel lblBloodPressure3;
    private javax.swing.JLabel lblDataofBirth;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDate3;
    private javax.swing.JLabel lblEmailAddresses;
    private javax.swing.JLabel lblFAXNumbe;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPulse1;
    private javax.swing.JLabel lblPulse3;
    private javax.swing.JLabel lblSocialSecurityNumber;
    private javax.swing.JLabel lblTelephoneNumbers;
    private javax.swing.JLabel lblTemp1;
    private javax.swing.JLabel lblTemp3;
    private javax.swing.JLabel lblgographicData;
    private javax.swing.JLabel lblgographicData1;
    private javax.swing.JTextField txtBankAccountNumbers;
    private javax.swing.JTextField txtBiometricIdentifiers;
    private javax.swing.JTextField txtCertificatecenseNumber;
    private javax.swing.JTextField txtDataofbirth;
    private javax.swing.JTextField txtDeviceIdentifiers;
    private javax.swing.JTextField txtEmailAdd;
    private javax.swing.JTextField txtFAXNumber;
    private javax.swing.JTextField txtGographicData;
    private javax.swing.JTextField txtHealthPlanBeneficiaryNumber;
    private javax.swing.JTextField txtInternetProtocolAddresses;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSocialSecurityNumber;
    private javax.swing.JTextField txtTelephoneNum;
    private javax.swing.JTextField txtUniqueCode;
    private javax.swing.JTextField txtVehicleIdentifiers;
    // End of variables declaration//GEN-END:variables
}
