/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.CreatePerson;
import Business.CreatePersonHistory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SUNREN
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private CreatePersonHistory cph;
    public ViewJPanel(CreatePersonHistory cph) {
        initComponents();
        this.cph = cph;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblVitalSign.getModel();
        dtm.setRowCount(0);
        
        for ( CreatePerson cp : cph.getCreatePHistory()){
            Object row[] = new Object[2];
            row[0] = cp;
            row[1] = cp.getSocialSecurityNumber();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblview = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitalSign = new javax.swing.JTable();
        btnViewDetail = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblDataofBirth = new javax.swing.JLabel();
        lblFAXNumbe = new javax.swing.JLabel();
        lblSocialSecurityNumber = new javax.swing.JLabel();
        lblTemp1 = new javax.swing.JLabel();
        lblBloodPressure1 = new javax.swing.JLabel();
        lblPulse1 = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        txtInternetProtocolAddresses = new javax.swing.JTextField();
        txtDeviceIdentifiers = new javax.swing.JTextField();
        txtCertificatecenseNumber = new javax.swing.JTextField();
        txtHealthPlanBeneficiaryNumber = new javax.swing.JTextField();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        txtFAXNumber = new javax.swing.JTextField();
        txtDataofbirth = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtGographicData = new javax.swing.JTextField();
        txtTelephoneNum = new javax.swing.JTextField();
        txtEmailAdd = new javax.swing.JTextField();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtBankAccountNumbers = new javax.swing.JTextField();
        txtVehicleIdentifiers = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtBiometricIdentifiers = new javax.swing.JTextField();
        lblDate3 = new javax.swing.JLabel();
        lblPulse3 = new javax.swing.JLabel();
        lblBloodPressure3 = new javax.swing.JLabel();
        lblTemp3 = new javax.swing.JLabel();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblEmailAddresses = new javax.swing.JLabel();
        lblTelephoneNumbers = new javax.swing.JLabel();
        lblgographicData = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblgographicData1 = new javax.swing.JLabel();
        txtUniqueCode = new javax.swing.JTextField();

        setEnabled(false);

        lblview.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        lblview.setForeground(new java.awt.Color(51, 51, 255));
        lblview.setText("View Detail");

        tblVitalSign.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Social SecurityNumber"
            }
        ));
        jScrollPane1.setViewportView(tblVitalSign);

        btnViewDetail.setText("View Detail");
        btnViewDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblName.setText("Name");

        lblDataofBirth.setText("Data of Birth");

        lblFAXNumbe.setText("FAX Number");

        lblSocialSecurityNumber.setText("Social Security Number");

        lblTemp1.setText("Health Plan Beneficiary Number");

        lblBloodPressure1.setText("Certificate cense Number");

        lblPulse1.setText("Device Identifiers");

        lblDate1.setText("Internet Protocol Addresses");

        txtInternetProtocolAddresses.setEnabled(false);
        txtInternetProtocolAddresses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInternetProtocolAddressesActionPerformed(evt);
            }
        });

        txtDeviceIdentifiers.setEnabled(false);
        txtDeviceIdentifiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceIdentifiersActionPerformed(evt);
            }
        });

        txtCertificatecenseNumber.setEnabled(false);
        txtCertificatecenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificatecenseNumberActionPerformed(evt);
            }
        });

        txtHealthPlanBeneficiaryNumber.setEnabled(false);
        txtHealthPlanBeneficiaryNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthPlanBeneficiaryNumberActionPerformed(evt);
            }
        });

        txtSocialSecurityNumber.setEnabled(false);

        txtFAXNumber.setEnabled(false);
        txtFAXNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAXNumberActionPerformed(evt);
            }
        });

        txtDataofbirth.setEnabled(false);
        txtDataofbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataofbirthActionPerformed(evt);
            }
        });

        txtName.setEnabled(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtGographicData.setEnabled(false);
        txtGographicData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGographicDataActionPerformed(evt);
            }
        });

        txtTelephoneNum.setEnabled(false);
        txtTelephoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNumActionPerformed(evt);
            }
        });

        txtEmailAdd.setEnabled(false);
        txtEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddActionPerformed(evt);
            }
        });

        txtMedicalRecordNumber.setEnabled(false);

        txtBankAccountNumbers.setEnabled(false);
        txtBankAccountNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccountNumbersActionPerformed(evt);
            }
        });

        txtVehicleIdentifiers.setEnabled(false);

        txtLinkedIn.setEnabled(false);
        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });

        txtBiometricIdentifiers.setEnabled(false);
        txtBiometricIdentifiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiometricIdentifiersActionPerformed(evt);
            }
        });

        lblDate3.setText("Biometric Identifiers");

        lblPulse3.setText("LinkedIn");

        lblBloodPressure3.setText("Vehicle Identifiers");

        lblTemp3.setText("Bank Account Numbers");

        lblMedicalRecordNumber.setText("Medical Record Number;");

        lblEmailAddresses.setText("Email Addresses");

        lblTelephoneNumbers.setText("Telephone Numbers");

        lblgographicData.setText("Gographic Data");

        lblImage.setText("Image not found");

        lblgographicData1.setText("Unique Code");

        txtUniqueCode.setEnabled(false);
        txtUniqueCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnViewDetail)
                                    .addComponent(btnDelete)
                                    .addComponent(txtGographicData, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lblview)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTemp1)
                            .addComponent(lblBloodPressure1)
                            .addComponent(lblPulse1)
                            .addComponent(lblDate1)
                            .addComponent(lblName)
                            .addComponent(lblDataofBirth)
                            .addComponent(lblFAXNumbe)
                            .addComponent(lblSocialSecurityNumber))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName)
                                .addComponent(txtDataofbirth)
                                .addComponent(txtFAXNumber)
                                .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDeviceIdentifiers)
                                .addComponent(txtCertificatecenseNumber)
                                .addComponent(txtHealthPlanBeneficiaryNumber)
                                .addComponent(txtInternetProtocolAddresses, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblgographicData)
                            .addComponent(lblTelephoneNumbers)
                            .addComponent(lblEmailAddresses)
                            .addComponent(lblMedicalRecordNumber)
                            .addComponent(lblTemp3)
                            .addComponent(lblBloodPressure3)
                            .addComponent(lblPulse3)
                            .addComponent(lblDate3)
                            .addComponent(lblgographicData1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUniqueCode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBankAccountNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTelephoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(txtEmailAdd))
                            .addComponent(txtVehicleIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBiometricIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnViewDetail))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(lblview)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(162, 162, 162)
                                    .addComponent(btnDelete))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGographicData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblgographicData))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelephoneNumbers)
                    .addComponent(txtTelephoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataofBirth)
                    .addComponent(txtDataofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailAddresses)
                    .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFAXNumbe)
                    .addComponent(txtFAXNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicalRecordNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSocialSecurityNumber)
                    .addComponent(lblTemp3)
                    .addComponent(txtBankAccountNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHealthPlanBeneficiaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblBloodPressure3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtVehicleIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCertificatecenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPulse3)
                                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeviceIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate3)
                            .addComponent(txtBiometricIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInternetProtocolAddresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblgographicData1)
                            .addComponent(txtUniqueCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTemp1)
                        .addGap(28, 28, 28)
                        .addComponent(lblBloodPressure1)
                        .addGap(28, 28, 28)
                        .addComponent(lblPulse1)))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailActionPerformed
        int selectedrow = tblVitalSign.getSelectedRow();
        if(selectedrow >= 0)
        {
            CreatePerson cp =(CreatePerson)tblVitalSign.getValueAt(selectedrow, 0);
            txtName.setText(cp.getName());
            txtDataofbirth.setText(cp.getDateOfBirth());
            txtTelephoneNum.setText(cp.getTelephoneNumbers());
            txtGographicData.setText(cp.getGographicData());
            txtSocialSecurityNumber.setText(cp.getSocialSecurityNumber());
            txtFAXNumber.setText(cp.getFAXNumber());
            txtEmailAdd.setText(cp.getEmailAddresses());
            txtSocialSecurityNumber.setText(cp.getSocialSecurityNumber());
            txtMedicalRecordNumber.setText(cp.getMedicalRecordNumber());
            txtHealthPlanBeneficiaryNumber.setText(cp.getHealthPlanBeneficiaryNumber());
            txtBankAccountNumbers.setText(cp.getBankAccountNumbers());
            txtCertificatecenseNumber.setText(cp.getCertificatecenseNumber());
            txtVehicleIdentifiers.setText(cp.getVehicleIdentifiers());
            txtDeviceIdentifiers.setText(cp.getDeviceIdentifiers());
            txtLinkedIn.setText(cp.getLinkedIn());
            txtInternetProtocolAddresses.setText(cp.getInternetProtocolAddresses());
            txtBiometricIdentifiers.setText(cp.getBiometricIdentifiers());
            txtUniqueCode.setText(cp.getUniqueCode());
            Icon icon =  new ImageIcon(cp.getFilePath());
            lblImage.setIcon(icon);
        }
        else
            JOptionPane.showMessageDialog(null, "Please select other.");
            
    }//GEN-LAST:event_btnViewDetailActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedrow = tblVitalSign.getSelectedRow();
        if(selectedrow >= 0)
        {
            CreatePerson cp =(CreatePerson)tblVitalSign.getValueAt(selectedrow, 0);
            cph.deleteVitals(cp);
            JOptionPane.showMessageDialog(null, "Success");
            populateTable();
        }
        else
            JOptionPane.showMessageDialog(null, "Please select other.");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtInternetProtocolAddressesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInternetProtocolAddressesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInternetProtocolAddressesActionPerformed

    private void txtDeviceIdentifiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceIdentifiersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdentifiersActionPerformed

    private void txtCertificatecenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificatecenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificatecenseNumberActionPerformed

    private void txtHealthPlanBeneficiaryNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthPlanBeneficiaryNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthPlanBeneficiaryNumberActionPerformed

    private void txtFAXNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAXNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAXNumberActionPerformed

    private void txtDataofbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataofbirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataofbirthActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtGographicDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGographicDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGographicDataActionPerformed

    private void txtTelephoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneNumActionPerformed

    private void txtEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddActionPerformed

    private void txtBankAccountNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccountNumbersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccountNumbersActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtBiometricIdentifiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiometricIdentifiersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiometricIdentifiersActionPerformed

    private void txtUniqueCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueCodeActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBloodPressure1;
    private javax.swing.JLabel lblBloodPressure3;
    private javax.swing.JLabel lblDataofBirth;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDate3;
    private javax.swing.JLabel lblEmailAddresses;
    private javax.swing.JLabel lblFAXNumbe;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPulse1;
    private javax.swing.JLabel lblPulse3;
    private javax.swing.JLabel lblSocialSecurityNumber;
    private javax.swing.JLabel lblTelephoneNumbers;
    private javax.swing.JLabel lblTemp1;
    private javax.swing.JLabel lblTemp3;
    private javax.swing.JLabel lblgographicData;
    private javax.swing.JLabel lblgographicData1;
    private javax.swing.JLabel lblview;
    private javax.swing.JTable tblVitalSign;
    private javax.swing.JTextField txtBankAccountNumbers;
    private javax.swing.JTextField txtBiometricIdentifiers;
    private javax.swing.JTextField txtCertificatecenseNumber;
    private javax.swing.JTextField txtDataofbirth;
    private javax.swing.JTextField txtDeviceIdentifiers;
    private javax.swing.JTextField txtEmailAdd;
    private javax.swing.JTextField txtFAXNumber;
    private javax.swing.JTextField txtGographicData;
    private javax.swing.JTextField txtHealthPlanBeneficiaryNumber;
    private javax.swing.JTextField txtInternetProtocolAddresses;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSocialSecurityNumber;
    private javax.swing.JTextField txtTelephoneNum;
    private javax.swing.JTextField txtUniqueCode;
    private javax.swing.JTextField txtVehicleIdentifiers;
    // End of variables declaration//GEN-END:variables
}
